# Generated by Django 5.0.3 on 2024-10-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('numero_adultos', models.PositiveIntegerField(verbose_name='Número de Adultos')),
                ('numero_ninos', models.PositiveIntegerField(default=0, verbose_name='Número de Niños')),
            ],
        ),
    ]
